import { Router, Request, Response } from 'express';
import { create } from 'youtube-dl-exec';
import { z } from 'zod';
import path from 'path';
import fs from 'fs';
import { cleanupFile } from '../utils/cleanup';
import ffmpegInstaller from '@ffmpeg-installer/ffmpeg';

const router = Router();

// Use the pip-installed yt-dlp which bypasses the PyInstaller Windows Security issue
const youtubedl = create('yt-dlp');

const tempOutDir = path.join(__dirname, '../../temp/downloads');
if (!fs.existsSync(tempOutDir)) {
  fs.mkdirSync(tempOutDir, { recursive: true });
}

const analyzeSchema = z.object({
  url: z.string().url(),
});

// Helper to determine source
const getSource = (url: string) => {
  if (url.includes('youtube.com') || url.includes('youtu.be')) return 'YouTube';
  if (url.includes('instagram.com/reel')) return 'Instagram Reel';
  if (url.includes('instagram.com/p')) return 'Instagram Post';
  return 'Direct Video';
};

router.post('/analyze', async (req: Request, res: Response): Promise<void> => {
  try {
    const { url } = analyzeSchema.parse(req.body);
    const source = getSource(url);
    
    // We only support YouTube and Instagram Reels for analysis
    if (source !== 'YouTube' && source !== 'Instagram Reel' && source !== 'Direct Video') {
      res.status(400).json({ error: "This source isn't currently supported." });
      return;
    }

    const info = await youtubedl(url, {
      dumpJson: true,
      noWarnings: true,
      noCheckCertificate: true,
      forceIpv4: true,
      noPlaylist: true,
    });

    const responseData = {
      title: info.title,
      duration: info.duration, // in seconds
      thumbnail: info.thumbnail,
      source: source,
      formats: [
        { type: 'mp4', quality: '720p', resolution: 720 },
        { type: 'mp4', quality: '480p', resolution: 480 },
        { type: 'mp4', quality: '360p', resolution: 360 },
      ].filter(f => {
        // filter out formats if not available, simplified for demo
        return info.formats?.some(fmt => fmt.height === f.resolution) || true; 
      }),
      audioFormats: [
        { type: 'mp3', quality: '192 kbps' }
      ]
    };

    res.json(responseData);
  } catch (error: any) {
    console.error('Error analyzing URL:', error);
    res.status(400).json({ error: "This content cannot be processed from this URL. Please use an authorized download option or upload the file directly." });
  }
});

router.get('/process', async (req: Request, res: Response): Promise<void> => {
  console.log('Received GET /process request', req.query);
  try {
    const url = req.query.url as string;
    const format = req.query.format as string;
    const quality = req.query.quality as string;
    
    if (!url || !format) {
      res.status(400).json({ error: 'URL and format are required' });
      return;
    }

    const outputFileName = `download-${Date.now()}.${format === 'mp3' ? 'mp3' : 'mp4'}`;
    const outputFilePath = path.join(tempOutDir, outputFileName);

    const downloadOptions: any = {
      output: outputFilePath,
      noWarnings: true,
      noCheckCertificate: true,
      forceIpv4: true, // Often speeds up connections
      noPlaylist: true, // Don't download entire playlists
      ffmpegLocation: ffmpegInstaller.path, // Pass ffmpeg path for merging
    };

    if (format === 'mp3') {
      downloadOptions.extractAudio = true;
      downloadOptions.audioFormat = 'mp3';
      downloadOptions.audioQuality = quality ? quality.split(' ')[0] : '192K';
    } else {
      // Basic best video+audio for mp4
      downloadOptions.format = 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best';
      downloadOptions.mergeOutputFormat = 'mp4';
    }

    console.log(`Starting download for ${url} to ${outputFilePath}`);
    await youtubedl(url, downloadOptions);

    console.log('Download complete, sending file...');
    
    if (fs.existsSync(outputFilePath)) {
      res.setHeader('Content-Disposition', `attachment; filename="${outputFileName}"`);
      res.setHeader('Content-Type', format === 'mp3' ? 'audio/mpeg' : 'video/mp4');
      
      const fileStream = fs.createReadStream(outputFilePath);
      fileStream.pipe(res);
      
      fileStream.on('end', () => {
        cleanupFile(outputFilePath);
      });
      
      fileStream.on('error', (err) => {
        console.error('Error streaming file:', err);
        cleanupFile(outputFilePath);
        if (!res.headersSent) res.status(500).end();
      });
      
      req.on('close', () => {
        cleanupFile(outputFilePath);
      });
    } else {
      throw new Error("File was not generated by yt-dlp.");
    }

  } catch (error) {
    console.error('Error processing download:', error);
    res.status(500).json({ error: 'Something went wrong while processing your file. Please try again.' });
  }
});

export default router;
